"""Palentir OSINT - Graph Builder Agent Example.

Demonstrates how to use the Graph Builder Agent to build a knowledge graph
from intelligence events generated by other agents.
"""

import asyncio
import logging
from datetime import datetime

from agents.graph_builder_agent import GraphBuilderAgent, IntelligenceEvent
from models.graph_nodes import NodeType, RelationType


# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)


async def simulate_social_media_agent():
    """Simulate Social Media Agent finding people."""
    logger.info("=== Social Media Agent ===")

    events = [
        IntelligenceEvent(
            event_type="person_found",
            source_agent="SocialMediaIntelligenceAgent",
            data={
                "name": "John Doe",
                "email": "john@example.com",
                "job_title": "Senior Software Engineer",
                "company": "Tech Corp",
                "location": "San Francisco, CA",
                "linkedin": "https://linkedin.com/in/johndoe",
                "twitter": "https://twitter.com/johndoe",
                "github": "https://github.com/johndoe",
                "connections": 1500,
                "followers": 500,
                "confidence": 0.95,
            },
        ),
        IntelligenceEvent(
            event_type="person_found",
            source_agent="SocialMediaIntelligenceAgent",
            data={
                "name": "Jane Smith",
                "email": "jane@example.com",
                "job_title": "Product Manager",
                "company": "Tech Corp",
                "location": "San Francisco, CA",
                "linkedin": "https://linkedin.com/in/janesmith",
                "twitter": "https://twitter.com/janesmith",
                "connections": 2000,
                "followers": 1000,
                "confidence": 0.92,
            },
        ),
    ]

    return events


async def simulate_company_agent():
    """Simulate Company Intelligence Agent finding companies."""
    logger.info("=== Company Intelligence Agent ===")

    events = [
        IntelligenceEvent(
            event_type="company_found",
            source_agent="CompanyIntelligenceAgent",
            data={
                "name": "Tech Corp",
                "industry": "Technology",
                "founded_year": 2010,
                "headquarters": "San Francisco, CA",
                "website": "https://techcorp.com",
                "employee_count": 500,
                "linkedin": "https://linkedin.com/company/techcorp",
                "twitter": "https://twitter.com/techcorp",
                "confidence": 0.98,
            },
        ),
    ]

    return events


async def simulate_domain_agent():
    """Simulate Domain Analysis Agent finding domains."""
    logger.info("=== Domain Analysis Agent ===")

    events = [
        IntelligenceEvent(
            event_type="domain_found",
            source_agent="DomainAnalysisAgent",
            data={
                "domain": "techcorp.com",
                "registrar": "GoDaddy",
                "registration_date": "2010-05-15",
                "expiration_date": "2026-05-15",
                "website_title": "Tech Corp - Innovative Solutions",
                "ssl_certificate": "Let's Encrypt",
                "ssl_issuer": "Let's Encrypt",
                "technologies": ["React", "Node.js", "PostgreSQL"],
                "confidence": 0.96,
            },
        ),
        IntelligenceEvent(
            event_type="domain_found",
            source_agent="DomainAnalysisAgent",
            data={
                "domain": "api.techcorp.com",
                "registrar": "GoDaddy",
                "registration_date": "2015-03-20",
                "website_title": "Tech Corp API",
                "ssl_certificate": "Let's Encrypt",
                "technologies": ["Node.js", "Express", "PostgreSQL"],
                "confidence": 0.94,
            },
        ),
    ]

    return events


async def simulate_network_agent():
    """Simulate Network Analyzer Agent finding IPs."""
    logger.info("=== Network Analyzer Agent ===")

    events = [
        IntelligenceEvent(
            event_type="ip_found",
            source_agent="NetworkAnalyzerAgent",
            data={
                "ip": "192.168.1.100",
                "country": "United States",
                "city": "San Francisco",
                "isp": "AWS",
                "asn": "16509",
                "open_ports": [80, 443, 22],
                "services": ["HTTP", "HTTPS", "SSH"],
                "technologies": ["nginx", "Node.js", "PostgreSQL"],
                "hosting_provider": "Amazon Web Services",
                "is_vpn": False,
                "is_proxy": False,
                "confidence": 0.97,
            },
        ),
    ]

    return events


async def simulate_relationship_agent(graph_builder: GraphBuilderAgent):
    """Simulate Relationship Builder Agent finding connections."""
    logger.info("=== Relationship Builder Agent ===")

    # Get current nodes to create relationships
    nodes, _ = await graph_builder.get_graph_snapshot()

    events = []

    # Find person and company nodes
    person_nodes = [n for n in nodes if n.metadata.node_type == NodeType.PERSON]
    company_nodes = [n for n in nodes if n.metadata.node_type == NodeType.COMPANY]
    domain_nodes = [n for n in nodes if n.metadata.node_type == NodeType.DOMAIN]
    ip_nodes = [n for n in nodes if n.metadata.node_type == NodeType.IP_ADDRESS]

    # Create person -> company relationships
    for person in person_nodes:
        for company in company_nodes:
            if person.metadata.company and person.metadata.company.lower() == company.metadata.label.lower():
                events.append(
                    IntelligenceEvent(
                        event_type="relationship_found",
                        source_agent="RelationshipBuilderAgent",
                        data={
                            "source_id": person.node_id,
                            "target_id": company.node_id,
                            "relationship_type": "works_at",
                            "label": "Works At",
                            "strength": 0.95,
                            "confidence": 0.95,
                            "evidence": f"{person.metadata.label} works at {company.metadata.label}",
                        },
                    )
                )

    # Create company -> domain relationships
    for company in company_nodes:
        for domain in domain_nodes:
            if company.metadata.website and company.metadata.website.endswith(domain.metadata.domain_name):
                events.append(
                    IntelligenceEvent(
                        event_type="relationship_found",
                        source_agent="RelationshipBuilderAgent",
                        data={
                            "source_id": company.node_id,
                            "target_id": domain.node_id,
                            "relationship_type": "owns",
                            "label": "Owns",
                            "strength": 0.98,
                            "confidence": 0.98,
                            "evidence": f"{company.metadata.label} owns {domain.metadata.domain_name}",
                        },
                    )
                )

    # Create domain -> IP relationships
    for domain in domain_nodes:
        for ip in ip_nodes:
            events.append(
                IntelligenceEvent(
                    event_type="relationship_found",
                    source_agent="RelationshipBuilderAgent",
                    data={
                        "source_id": domain.node_id,
                        "target_id": ip.node_id,
                        "relationship_type": "hosted_on",
                        "label": "Hosted On",
                        "strength": 0.90,
                        "confidence": 0.90,
                        "evidence": f"{domain.metadata.domain_name} is hosted on {ip.metadata.label}",
                    },
                )
            )

    return events


async def main():
    """Main example."""
    logger.info("Starting Graph Builder Agent Example")

    # Initialize Graph Builder Agent
    graph_builder = GraphBuilderAgent()

    try:
        # Simulate agents generating intelligence events
        logger.info("\n=== Phase 1: Social Media Intelligence ===")
        social_events = await simulate_social_media_agent()
        for event in social_events:
            result = await graph_builder.process_event(event)
            logger.info(f"Result: {result}")
            await asyncio.sleep(0.5)

        logger.info("\n=== Phase 2: Company Intelligence ===")
        company_events = await simulate_company_agent()
        for event in company_events:
            result = await graph_builder.process_event(event)
            logger.info(f"Result: {result}")
            await asyncio.sleep(0.5)

        logger.info("\n=== Phase 3: Domain Analysis ===")
        domain_events = await simulate_domain_agent()
        for event in domain_events:
            result = await graph_builder.process_event(event)
            logger.info(f"Result: {result}")
            await asyncio.sleep(0.5)

        logger.info("\n=== Phase 4: Network Analysis ===")
        network_events = await simulate_network_agent()
        for event in network_events:
            result = await graph_builder.process_event(event)
            logger.info(f"Result: {result}")
            await asyncio.sleep(0.5)

        logger.info("\n=== Phase 5: Relationship Building ===")
        relationship_events = await simulate_relationship_agent(graph_builder)
        for event in relationship_events:
            result = await graph_builder.process_event(event)
            logger.info(f"Result: {result}")
            await asyncio.sleep(0.5)

        # Get final graph snapshot
        logger.info("\n=== Final Graph Snapshot ===")
        nodes, edges = await graph_builder.get_graph_snapshot()

        logger.info(f"Total Nodes: {len(nodes)}")
        logger.info(f"Total Edges: {len(edges)}")

        # Display nodes
        logger.info("\nNodes:")
        for node in nodes:
            logger.info(
                f"  - {node.metadata.label} ({node.metadata.node_type.value}) "
                f"[confidence: {node.metadata.confidence:.2f}]"
            )

        # Display edges
        logger.info("\nEdges:")
        for edge in edges:
            logger.info(
                f"  - {edge.metadata.source_id} -> {edge.metadata.label} -> "
                f"{edge.metadata.target_id} [strength: {edge.metadata.strength:.2f}]"
            )

        # Get Graphistry URL
        logger.info("\n=== Graphistry Visualization ===")
        graphistry_url = await graph_builder.get_graphistry_url()
        if graphistry_url:
            logger.info(f"Graphistry URL: {graphistry_url}")
        else:
            logger.info("Graphistry not available")

    finally:
        await graph_builder.close()

    logger.info("\nExample completed")


if __name__ == "__main__":
    asyncio.run(main())
